type: single # single|window, maybe add opt
key: tagnn #added to the csv names
evaluation: evaluation #evaluation|evaluation_last|evaluation_multiple|evaluation_user_based|evaluation_user_based_multiple
data:
  name: diginetica #added in the end of the csv names
  folder: data/diginetica/fulltrain/
  prefix: diginetica
results:
  folder: results/
metrics:
- class: accuracy.MRR
  length: [3,5,10,15,20]
- class: accuracy.HitRate
  length: [3,5,10,15,20]
- class: coverage.Coverage
  length: [20]
- class: popularity.Popularity
  length: [20]
- class: saver.Saver
  length: [50]
- class: time_memory_usage.Time_usage_training
- class: time_memory_usage.Time_usage_testing
algorithms:
- class: TAGNN.TAGNN.TAGNN
  params: {epoch: 20, lr: 0.0007, batch_size: 100, embedding_size: 100, l2: 0.00001}
  key: TAGNN
